version: '3.0'
services:
  server:
    build: "./server"
    container_name: "server"
    ports: 
      - "3000:3000"
  frontend:
    build: "./client"
    container_name: "frontend"
    ports:
      - "8080:8080"
  terraform:
    image: hashicorp/terraform:0.14.10
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}