version: '3.0'
services:
  server:
    build: "./server"
    container_name: "server"
    ports: 
      - "3000:3000"
  frontend:
    build: "./client"
    container_name: "frontend"
    ports:
      - "8080:8080"